### ISSUE TITLE
how to install this

### ISSUE THREAD

**Issue by chongxi** [linux-surface/surface-hotplug#2]
Is there an instruction to help installing this driver?

**Comment by qzed** [comment]
If you want to install this manually, you'll have to build a custom kernel with the patches in the `patches/` directory applied and then build the module from the `module/` directory via `make dkms-install`.

However, I suggest you just install the [linux-surface kernel](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup) instead, which contains this driver.
